### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: No available storage method found

### ISSUE THREAD

**Issue by Wind213** [MacKentoch/react-redux-nextjs-material-ui-pwa-starter#2]
### Version
1.2.0

### Node JS
v9.11.1

### Browser
Chrome 65.0.3325.181

### OS version
windows 10

I'm really excited with this project but first installation give me this error, do you mind give me some direction

**Comment by MacKentoch** [comment]
hi @Wind213 

Thank you for submitting the issue.
I fixed master branch.

This was due to `localForage`... 
so as a fix I better use now `asyncLocalStorage` from `redux-persist`.

There are few warnings left but these are related to the default css in js styling librairy coming with material UI.

I better use `styled-component`(*I really dislike the default option, yes subjective but important*) so I may soon migrate to styled-components
